#test exception 8
int main()
{
	var x : int;
	x = 1 / 0;
	return x;
}