#test exception 8
#floating point exception

int 
main()
{
   return (1) % (1 ^ 1);
}
