#test exception 8

int main(){
  return 5 / (3 == 4);
}
